# docker-compose.yaml v4.1 - Final Integrated Stack

services:
  dataroom-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - dataroom-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  intent-parser:
    build: ./agents/intent-parser
    image: vltrn/intent-parser:1.0.0
    ports:
      - "4000:4000"
    # This service must have access to the docker socket to launch other agents
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      dataroom-db:
        condition: service_healthy

  scout-warn:
    build: ./agents/scout-warn
    image: vltrn/scout-warn:1.0.0
    env_file: .env
    # This service is run on-demand by the orchestrator, so we don't start it automatically
    deploy:
      replicas: 0

  marketer-agent:
    build: ./agents/marketer-agent
    image: vltrn/marketer-agent:1.0.0
    env_file: .env
    # This service is also run on-demand
    deploy:
      replicas: 0

volumes:
  dataroom-data: