services:
  dataroom-db:
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "15432:5432"
    volumes:
      - dataroom-data:/var/lib/postgresql/data

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      dataroom-db:
        condition: service_healthy

  scout-warn:
    build:
      context: ./agents/scout-warn
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      dataroom-db:
        condition: service_healthy

  marketer-agent:
    build:
      context: ./agents/marketer-agent
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      dataroom-db:
        condition: service_healthy

volumes:
  dataroom-data: {}
