# kubernetes/marketer-agent-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: marketer-agent-run
spec:
  template:
    spec:
      containers:
      - name: marketer-agent
        # Use the container image we built for the marketer agent.
        image: vltrn/marketer-agent:1.0.0
        # This injects all keys (DB, Google, GitHub) from our comprehensive 
        # secret as environment variables into the container.
        envFrom:
        - secretRef:
            name: vltrn-secrets
      # This policy ensures that if the job fails, it will not automatically restart.
      restartPolicy: Never
  backoffLimit: 4