apiVersion: batch/v1
kind: Job
metadata:
  name: scout-warn-run
spec:
  template:
    spec:
      containers:
      - name: scout-warn-agent
        image: ghcr.io/morpheous/scout-warn:1.0.0
        envFrom:
        - secretRef:
            name: vltrn-secrets
      restartPolicy: Never
  backoffLimit: 4
